# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrganMatching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
